name: ci

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build_image:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
          
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7

      - id: set_version
        run: echo "::set-output name=version::${{ env.GITVERSION_SEMVER }}"

      - name: Tag commit
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.GITVERSION_SEMVER }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        run: docker build . -t ghcr.io/wattcode/globe-viz:latest -t ghcr.io/wattcode/globe-viz:${{ env.GITVERSION_SEMVER }}

      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "ghcr.io/wattcode/globe-viz:${{ env.GITVERSION_SEMVER }}"

  create_package:
    needs: build_image
    if: ${{ github.ref == 'refs/heads/main'  }}
    runs-on: ubuntu-latest
    steps:
      - id: archive 
        name: Download image
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "ghcr.io/wattcode/globe-viz:${{ needs.build_image.outputs.version }}"

      - id: set_image_name
        run: echo "::set-output name=image::${{ env.GITVERSION_SEMVER }}"

      - name: Load image
        run: docker load -i ${{ steps.archive.outputs.download_path }}

      - name: Tag as latest
        run: docker tag ghcr.io/wattcode/globe-viz:${{ needs.build_image.outputs.version }} ghcr.io/wattcode/globe-viz:latest

      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u wattcode --password-stdin

      - name: Publish
        run: docker push -a ghcr.io/wattcode/globe-viz